apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume
  namespace: resume
  labels:
    app: resume
spec:
  replicas: 2
  selector:
    matchLabels:
      app: resume
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: resume
    spec:
      containers:
        - name: resume
          command: ["node", "server.js"]
          ports:
            - containerPort: 3456
          livenessProbe:
            httpGet:
              path: /
              port: 3456
            initialDelaySeconds: 3
            failureThreshold: 30
            periodSeconds: 3
          resources:
            limits:
              cpu: 250m
              ephemeral-storage: 1Gi
              memory: 512Mi
            requests:
              cpu: 250m
              ephemeral-storage: 1Gi
              memory: 512Mi
