name: Deployment

on:
  push:
    branches: "master"

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}

jobs:
  build-and-push-resume:
    name: "Build & Push"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: ghcr.io/dtheng/resume
          flavor: latest=true
          tags: value=${{ github.sha }}
      - uses: docker/build-push-action@v4
        with:
          file: ./../../Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  upload-pdf-resume:
    name: "Upload PDF"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: "google-github-actions/auth@v1"
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: npm run build
        working-directory: ./pdf-gen
        run: |
          npm ci
          npm run build
      - uses: "google-github-actions/upload-cloud-storage@v1"
        with:
          path: "pdf-gen/tmp/DanielThengvallResume.pdf"
          destination: "com-dtheng"
          process_gcloudignore: false
  upload-profile-image:
    name: "Upload Profile Image"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: "google-github-actions/auth@v1"
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}
      - uses: "google-github-actions/upload-cloud-storage@v1"
        with:
          path: "profile.jpg"
          destination: "com-dtheng"
          process_gcloudignore: false
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    needs: build-and-push-resume
    steps:
      - uses: actions/checkout@v3
      - uses: "google-github-actions/auth@v1"
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}
      - uses: "google-github-actions/setup-gcloud@v1"
      - uses: "google-github-actions/get-gke-credentials@v1"
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER_2 }}
          location: ${{ secrets.GKE_ZONE_2 }}
      - uses: fjogeleit/yaml-update-action@v0.13.1
        with:
          valueFile: "resume.yml"
          propertyPath: "spec.template.spec.containers[0].image"
          value: ghcr.io/dtheng/resume:${{ github.sha }}
          commitChange: false
      - name: Start Deployment
        run: kubectl apply -f resume.yml --namespace=resume
      - name: Wait for Completion
        run: kubectl rollout status --timeout=480s deployment/resume --namespace=resume
