name: Deployment

on:
  push:
    branches: "*"

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}

jobs:
  build-and-push-resume:
    name: "Build & Push Resume"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          file: ./../../resume.Dockerfile
          push: true
          tags: dtheng/resume:latest, dtheng/resume:${{ github.sha }}
  upload-pdf-resume:
    name: "Upload PDF Resume"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: "google-github-actions/auth@v1"
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: npm run build
        working-directory: ./pdf-gen
        run: |
          npm ci
          npm run build
          pwd
          cd tmp
          ls

    # - uses: 'google-github-actions/upload-cloud-storage@v1'
    #   with:
    #     path: '/path/to/file'
    #     destination: 'bucket-name/file'
